### ISSUE TITLE
Works well except no way to insert null

### ISSUE THREAD

**Issue by codebyray** [haruncpi/db-seeder#1]
Hello,

First let me say thank you for sharing this great tool.

I am running into an issue however when inserting data. How do I tell the program NOT to enter data into a particular column? For instance, if I have a deleted_at column for soft deletes, I DO NOT want a date inserted, rather I want it to be NULL.

Is there a way to insert NULL instead of a date, or insert NULL on any column I do not want seeded?

Thank you in advance for your assistance.

Regards,
Ray

**Comment by haruncpi** [comment]
Select **constant** data type and type **(NULL)** as a constant value.
