### ISSUE TITLE
DMG Installation fails on Mac - dbseeder-1.0.1.dmg

### ISSUE THREAD

**Issue by lcallif** [haruncpi/db-seeder#5]
Error upon running it after the installation: 
<img width="426" alt="Screen Shot 2020-08-15 at 2 16 56 PM" src="https://user-images.githubusercontent.com/1018074/90320887-067ceb00-df02-11ea-80b8-2d33e934681c.png">
“dbseeder” cannot be opened because the developer cannot be verified.

**Comment by rimbaborne** [comment]
up

**Comment by haruncpi** [comment]
Follow the updated doc
https://github.com/haruncpi/db-seeder
