### ISSUE TITLE
DBSeeder unable to connect to localhost mysql server

### ISSUE THREAD

**Issue by mrthankyou** [haruncpi/db-seeder#8]
## What's the Problem
I'm unable to connect the DBSeeder application to my mysql localhost server. I am able to connect to the MySQL server via other applications and via terminal. 

## Screenshot(s)
<img width="1266" alt="Screen Shot 2021-10-16 at 2 34 32 PM" src="https://user-images.githubusercontent.com/52643283/137598593-a70e7382-b853-4b9a-89e4-1cb0f2a0e787.png">

## Anything Else You Should Know
If you require any additional information please let me know.

**Comment by olleharstedt** [comment]
Same problem here, root user, empty password. Connection to MySQL works fine from command line. Running Ubuntu.

**Comment by officialdave** [comment]
Add a password and all should work fine.
